### ISSUE TITLE
can not work with logic 1.2.18

### ISSUE THREAD

**Issue by szneilsun** [pfrench42/saleae_spdif#2]
i can use the logic to get the wave from SPDIF interface, and set the protocol as SPDIF, but there is no ouput in decoder panel. 
![image](https://user-images.githubusercontent.com/541099/68575123-6394cd80-04a6-11ea-8279-6f356975d004.png)

**Comment by pfrench42** [comment]
The source code contains a fix for the decoder, but I've not published a binary update for the library, are you running on linux or windows?

**Comment by szneilsun** [comment]
thanks for update, i am using windows to decode SPDIF data. is it possible to share the bin file with me to sucessfully fix this problem?
